---
include: https://raw.githubusercontent.com/hassio-addons/organization/master/gitlabci/addon.yml

variables:
  ADDON_GITHUB_REPO: "hassio-addons/addon-base"
  ADDON_SLUG: "base"
  ADDON_TARGET: "base"

  ADDON_LEGACY_TAGS: "true"
  ADDON_PUBLISH: "false"
  ADDON_QEMU: "true"

  ADDON_AARCH64_BASE: "arm64v8/alpine:3.9.3"
  ADDON_AMD64_BASE: "amd64/alpine:3.9.3"
  ADDON_ARMHF_BASE: "arm32v6/alpine:3.9.3"
  ADDON_ARMV7_BASE: "arm32v7/alpine:3.9.3"
  ADDON_I386_BASE: "i386/alpine:3.9.3"
